import React, { useMemo, useState } from 'react'

function OntologyObjectResourceDrawer({ mode, object, objects = [], properties = [], relations = [], onClose, onBind, onUnbind }) {
  const isProperty = mode === 'property'
  const [selectedIds, setSelectedIds] = useState([])
  const [targetObjectId, setTargetObjectId] = useState(objects.find((item) => item.id !== object.id)?.id || '')
  const [relationName, setRelationName] = useState('')
  const [relationApiName, setRelationApiName] = useState('')
  const [cardinality, setCardinality] = useState('多对一')
  const boundResources = useMemo(() => (isProperty ? properties : relations).filter((item) => isProperty ? (item.objectIds || [item.objectId]).includes(object.id) : item.sourceObjectId === object.id || item.targetObjectId === object.id), [isProperty, object.id, properties, relations])
  const availableProperties = properties.filter((item) => !boundResources.some((bound) => bound.id === item.id))
  const targetObjects = objects.filter((item) => item.id !== object.id)
  const toggleProperty = (id) => setSelectedIds((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id])
  const createRelation = () => {
    if (!targetObjectId || !relationName.trim() || !relationApiName.trim()) return
    onBind({ name: relationName.trim(), apiName: relationApiName.trim(), sourceObjectId: object.id, targetObjectId, cardinality })
    setRelationName('')
    setRelationApiName('')
  }

  return <div className="fixed inset-0 z-[100] bg-[#17191f]/30" onMouseDown={onClose}>
    <aside className="ml-auto flex h-full w-full max-w-[540px] flex-col overflow-y-auto border-l border-[#e7e9ed] bg-white shadow-[-20px_0_70px_rgba(15,23,42,0.18)]" onMouseDown={(event) => event.stopPropagation()}>
      <div className="flex items-start justify-between border-b border-[#eceef1] bg-[linear-gradient(180deg,#ffffff_0%,#fffafa_100%)] px-6 py-5"><div><p className="text-xs font-semibold text-[#d94338]">{isProperty ? 'OBJECT PROPERTIES' : 'OBJECT RELATIONS'}</p><h2 className="mt-1 text-lg font-semibold text-[#20242b]">{object.name}的{isProperty ? '属性' : '关联'}</h2><p className="mt-1 text-xs text-[#858d98]">{isProperty ? '可多选已有属性进行绑定，也可以逐条解除绑定。' : '选择目标对象创建关联，也可以删除当前对象发出的关联。'}</p></div><button type="button" onClick={onClose} className="h-9 w-9 text-xl text-[#7b828c]" aria-label="关闭">×</button></div>
      <div className="flex-1 space-y-6 px-6 py-6">
        <section><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold text-[#343a43]">已绑定{isProperty ? '属性' : '关联'}</h3><span className="text-xs text-[#858d98]">{boundResources.length} 个</span></div>{boundResources.length ? <div className="divide-y border border-[#e0e3e7]">{boundResources.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 px-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-[#303741]">{item.name}</p><p className="mt-1 truncate text-xs text-[#858d98]">{isProperty ? `${item.dataType || '文本'} · ${item.description || '暂无说明'}` : `${objects.find((entry) => entry.id === item.sourceObjectId)?.name || '来源对象'} → ${objects.find((entry) => entry.id === item.targetObjectId)?.name || '目标对象'} · ${item.cardinality || '未设置'}`}</p></div><button type="button" onClick={() => onUnbind(item)} className="shrink-0 text-xs font-medium text-[#d94338]">删除绑定</button></div>)}</div> : <div className="border border-dashed border-[#cfd5dc] px-4 py-6 text-center text-sm text-[#858d98]">当前对象还没有绑定{isProperty ? '属性' : '关联'}</div>}</section>
        {isProperty ? <section><div className="mb-3 flex items-center justify-between"><h3 className="text-sm font-semibold text-[#343a43]">选择已有属性</h3><span className="text-xs text-[#858d98]">可多选</span></div>{availableProperties.length ? <div className="divide-y border border-[#e0e3e7]">{availableProperties.map((item) => <label key={item.id} className="flex cursor-pointer items-center gap-3 px-4 py-3 hover:bg-[#fff8f6]"><input type="checkbox" checked={selectedIds.includes(item.id)} onChange={() => toggleProperty(item.id)} className="h-4 w-4 accent-[#e3473c]" /><span className="min-w-0"><span className="block truncate text-sm font-medium text-[#303741]">{item.name}</span><span className="mt-1 block truncate text-xs text-[#858d98]">{item.dataType || '文本'} · {item.description || '暂无说明'}</span></span></label>)}</div> : <div className="border border-dashed border-[#cfd5dc] px-4 py-6 text-center text-sm text-[#858d98]">暂无可绑定的已有属性。</div>}</section> : <section><h3 className="mb-3 text-sm font-semibold text-[#343a43]">新增关联</h3><div className="space-y-4"><label className="block text-sm"><span className="mb-2 block font-medium text-[#343a43]">目标对象 *</span><select value={targetObjectId} onChange={(event) => setTargetObjectId(event.target.value)} className="h-11 w-full rounded-md border border-[#d9dde3] bg-white px-3.5">{targetObjects.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block text-sm"><span className="mb-2 block font-medium text-[#343a43]">关系名称 *</span><input value={relationName} onChange={(event) => setRelationName(event.target.value)} placeholder="例如：属于生产计划" className="h-11 w-full rounded-md border border-[#d9dde3] px-3.5" /></label><label className="block text-sm"><span className="mb-2 block font-medium text-[#343a43]">API Name *</span><input value={relationApiName} onChange={(event) => setRelationApiName(event.target.value)} placeholder="belongsToPlan" className="h-11 w-full rounded-md border border-[#d9dde3] px-3.5 font-mono" /></label><label className="block text-sm"><span className="mb-2 block font-medium text-[#343a43]">关系基数</span><select value={cardinality} onChange={(event) => setCardinality(event.target.value)} className="h-11 w-full rounded-md border border-[#d9dde3] bg-white px-3.5"><option>一对一</option><option>一对多</option><option>多对一</option><option>多对多</option></select></label><button type="button" onClick={createRelation} disabled={!targetObjectId || !relationName.trim() || !relationApiName.trim()} className="h-10 w-full rounded-md bg-[#fff0ed] text-sm font-medium text-[#d94338] disabled:cursor-not-allowed disabled:opacity-50">新增这条关联</button></div></section>}
      </div>
      <div className="flex justify-end gap-3 border-t border-[#eceef1] bg-[#fcfcfd] px-6 py-4"><button type="button" onClick={onClose} className="h-10 rounded-md border border-[#d9dde3] bg-white px-5 text-sm text-[#4d545e]">关闭</button>{isProperty && <button type="button" disabled={!selectedIds.length} onClick={() => { onBind(selectedIds); setSelectedIds([]) }} className="h-10 rounded-md bg-[#e3473c] px-5 text-sm font-medium text-white disabled:cursor-not-allowed disabled:bg-[#e7a6a0]">添加 {selectedIds.length || ''} 条绑定</button>}</div>
    </aside>
  </div>
}

export default OntologyObjectResourceDrawer
